# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan's Blog
author: Jordan Bisasky
email: jordan.bisasky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chronicling the development of a full stack web and mobile application. From
  concept to design to development to deployment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jbisasky.github.io/" # the base hostname & protocol for your site
twitter_username: TheJbLounge
github_username:  jbisasky

# Build settings
markdown: kramdown
